dev flake
nix-community/srvos pull request #350
Opened 2024-01-01 02:05 UTC by zowoq

2024-01-01 11:05 UTC, zimbatm requested changes
What problem does it solve? Please add more details to your commit messages so it's possible to follow the reasoning.

2024-01-01 11:27 UTC, zowoq commented
It allows us to have private dev inputs that we can use in the main flake, can then move the github actions checks to buildbot. We discussed this briefly on matrix a few weeks ago.

2024-01-06 00:30 UTC, zowoq commented
I plan to merge this before the next flake update.

2024-01-13 23:08 UTC, merged

2024-01-13 23:31 UTC, zowoq commented on .github/workflows/update-flake-lock.yml
> +        #    merge-queue
I'll merge these manually for now, will re-enable this in a week or two.